# Generated by Django 4.1.7 on 2023-03-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=65536, verbose_name='Password')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked?')),
                ('block_reason', models.CharField(choices=[('You have been blocked by an administrator', 'By Admin'), ('You have been blocked for cheating', 'By Cheating'), ('You have been blocked for spamming', 'By Spamming')], max_length=128, null=True, verbose_name='Block Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
