# Generated by Django 4.1.7 on 2023-03-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_reason',
            field=models.CharField(blank=True, choices=[('You have been blocked by an administrator', 'By Admin'), ('You have been blocked for cheating', 'By Cheating'), ('You have been blocked for spamming', 'By Spamming')], max_length=128, null=True, verbose_name='Block Reason'),
        ),
    ]
