# Generated by Django 4.1.7 on 2023-03-09 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 14, 36, 24, 664554), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 14, 36, 24, 664568), verbose_name='Last Login'),
        ),
    ]
