# Generated by Django 4.1.7 on 2023-03-09 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_at_last_login_as_editable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 14, 53, 57, 47723), verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 9, 14, 53, 57, 47737), verbose_name='Last Login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
