# Generated by Django 4.1.7 on 2023-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, verbose_name='Username')),
                ('password', models.CharField(max_length=65536, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked?')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
        ),
    ]
