# Generated by Django 4.1.7 on 2023-03-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_author_alter_score_user'),
        ('authorization', '0004_remove_user_is_deleted_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
