# Generated by Django 4.1.7 on 2023-03-22 06:14

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('thumbnail', models.ImageField(null=True, upload_to=games.models.Game._directory_path, verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='users.user', verbose_name='Author')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('highest', models.BooleanField(verbose_name='Highest?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game', verbose_name='Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='users.user', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('source', models.FileField(upload_to=games.models.GameVersion._get_source_path, verbose_name='Source Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(condition=models.Q(('highest', True)), fields=('game_id', 'user_id'), name='unique_highest_game_score_per_player'),
        ),
    ]
