# Generated by Django 4.1.7 on 2023-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
