# Generated by Django 4.1.7 on 2023-04-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameversion',
            unique_together={('game', 'version')},
        ),
    ]
