# Generated by Django 4.1.7 on 2023-02-21 13:09

from django.db import migrations, models
import django.utils.timezone
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_set_slug_as_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(default='media/games/default.png', upload_to=games.models.Game._directory_path, verbose_name='Thumbnail'),
        ),
    ]
