# Generated by Django 4.1.7 on 2023-03-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_set_game_thumbnail_as_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(verbose_name='Slug'),
        ),
    ]
