# Generated by Django 4.1.7 on 2023-03-08 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('games', '0007_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='users.user', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='users.user', verbose_name='User'),
        ),
    ]
