# Generated by Django 4.1.7 on 2023-03-08 15:44

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_game_author_alter_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='source',
        ),
        migrations.RemoveField(
            model_name='game',
            name='version',
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='', verbose_name='Thumbnail'),
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Version')),
                ('source', models.FileField(upload_to=games.models.GameVersion._get_source_path, verbose_name='Source Code')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Game')),
            ],
        ),
    ]
