# Generated by Django 4.1.7 on 2023-03-09 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_split_game_and_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game', verbose_name='Game'),
        ),
    ]
