# Generated by Django 4.1.7 on 2023-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_gameversion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(verbose_name='Score'),
        ),
    ]
